### PR TITLE
Refreshed demo project

### PR DESCRIPTION
**Pull request by valentinyanakiev**
- fixed outstanding organiSation issues
- updated outdated dependencies
- added missing services

### CODE REVIEW

**Review by techsmyth — CHANGES_REQUESTED** [review]
Looks generally good. Would love later to get a way to share the kratos templates....

Two updates:
- auth should still be disabled imho for now
- we need a solution to the synapse permissions issue. 
Lets chat about both later.

**Comment by valentinyanakiev** [comment]
> Looks generally good. Would love later to get a way to share the kratos templates....
> 
> Two updates:
> 
> * auth should still be disabled imho for now
> * we need a solution to the synapse permissions issue.
>   Lets chat about both later.

Auth cannot be disabled if we want communications. Altogether, I believe this flag should be removed - there is WAY too much dependent on the user and user-agent now. Communications module also depends on it - if AUTH_ENABLED=false, even if COMMUNICATIONS_ENABLED=true, it won't work, which is rather confusing as well.

**Comment by valentinyanakiev** [comment]
Now population with AUTH_ENABLED=true works. There is a data issue thou because data validation (I guess a field was made mandatory)... How do we proceed?

image

**Comment by valentinyanakiev** [comment]
Built the server image with the latest set of changes on pushed them to my local dockerhub account. The branch is demo-120-test and works fine for me.

**Review by techsmyth — APPROVED** [review]

**Pull request merged**
